name: CI

on:
  pull_request:

env:
  GOTOOLCHAIN: local

jobs:
  tests_go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.10'

      - name: Go Mod Download
        run: go mod download

      - name: Test
        run: make test && make cover
